use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use genanki_rs::{Deck, Model, Note, Package, Field, Template};
use crate::models::{RE_THEMA, EntryData};
use crate::utils::{clean_german_for_audio, colorize_gender, highlight_word_in_example};

pub fn get_num(s: &str) -> i32 {
    RE_THEMA
        .captures(s)
        .and_then(|c| c.get(1))
        .and_then(|m| m.as_str().parse().ok())
        .unwrap_or(0)
}

pub fn generate_decks(
    files: &[PathBuf],
    base_name: &str,
    format_type: &str,
    quizlet_minimal: bool,
) -> (usize, usize, Vec<String>) {
    let mut all_entries = Vec::new();
    let mut unique_entries_str = Vec::new();
    let mut seen: HashMap<String, String> = HashMap::new();
    let mut web_data = Vec::new();
    let mut warnings = Vec::new();

    // Define Anki Model (Note Type) with Multi-language TTS support
    let model = Model::new(
        1607392319,
        "German B2 Professional",
        vec![
            Field::new("German"),
            Field::new("German_Audio"),
            Field::new("English"),
            Field::new("English_Audio"), // New field for clean English TTS
            Field::new("Ukrainian"),
            Field::new("Example"),
            Field::new("Example_Audio"), // New field for clean Example TTS
            Field::new("Tags"),
        ],
        vec![Template::new("Card 1")
            .qfmt("<div style='font-family: \"Outfit\", sans-serif; text-align: center; color: #f8fafc; background-color: #0f172a; padding: 40px; border-radius: 20px;'>\
                    <div style='font-size: 32px; font-weight: 600; margin-bottom: 20px;'>{{German}}</div>\
                    <div style='display: none;'>{{tts de_DE:German_Audio}}</div>\
                   </div>")
            .afmt("{{FrontSide}}<hr id='answer'>\
                   <div style='font-family: \"Outfit\", sans-serif; text-align: center; color: #f8fafc; background-color: #1e293b; padding: 40px; border-radius: 20px;'>\
                    <div style='font-size: 24px; color: #00d2ff; margin-bottom: 15px;'>{{English}}</div>\
                    <div style='display: none;'>{{tts en_US:English_Audio}}</div>\
                    <div style='font-size: 24px; color: #22c55e; margin-bottom: 25px;'>{{Ukrainian}}</div>\
                    <div style='font-style: italic; color: #cbd5e1; font-size: 18px; border-top: 1px solid #334155; padding-top: 20px;'>{{Example}}</div>\
                    <div style='margin-top: 25px;'>\
                        <div style='display: inline-block; margin: 0 10px;'>{{tts de_DE:German_Audio}}</div>\
                        <div style='display: inline-block; margin: 0 10px;'>{{tts de_DE:Example_Audio}}</div>\
                    </div>\
                   </div>")
        ],
    ).css(".card { font-family: 'Outfit', sans-serif; background-color: #0f172a; }");

    let deck_id = match base_name {
        "B1plus" => 1607392320,
        "B2" => 1607392321,
        _ => 1607392322,
    };
    let mut deck = Deck::new(deck_id, &format!("German {}", base_name), "Deck generated by rs_build");

    for f_path in files {
        let content = fs::read_to_string(f_path).unwrap_or_default();
        let fname = f_path.file_name().unwrap().to_string_lossy().to_string();

        for (i, line) in content.lines().enumerate() {
            let l = line.trim();
            if l.is_empty() || l.starts_with('#') {
                continue;
            }
            let parts: Vec<&str> = l.split(';').map(|s| s.trim()).collect();
            if parts.len() < 3 {
                warnings.push(format!("{}:{}: Less than 3 columns", fname, i + 1));
                continue;
            }

            let word_display = parts[0].to_string();
            let word_audio = clean_german_for_audio(&word_display);
            let english = parts[1].to_string();
            let ukrainian = parts[2].to_string();
            let example_raw = if parts.len() > 3 { parts[3].to_string() } else { String::new() };

            let level = if fname.contains("B1_plus") { "B1+".to_string() } else { "B2".to_string() };
            let thema = get_num(&fname);
            let entry_tag = format!("{} Thema{}", level, thema).replace("+", "plus");

            let german_colored = colorize_gender(&word_display);
            let example_html = highlight_word_in_example(&word_audio, &example_raw);

            let entry_data = EntryData {
                level: level.clone(),
                thema,
                german: german_colored.clone(),
                german_audio: word_audio.clone(),
                english: english.clone(),
                ukrainian: ukrainian.clone(),
                example: example_html.clone(),
            };

            if format_type == "anki" {
                let note = Note::new(model.clone(), vec![
                    &german_colored,
                    &word_audio,
                    &english,
                    &english,         // English_Audio (clean text)
                    &ukrainian,
                    &example_html,
                    &example_raw,     // Example_Audio (clean text)
                    &entry_tag,
                ]).unwrap();
                
                all_entries.push(german_colored.clone());
                if !seen.contains_key(&word_display) {
                    deck.add_note(note);
                    seen.insert(word_display.clone(), fname.clone());
                    unique_entries_str.push(german_colored.clone());
                    if base_name == "B1plus_B2" {
                        web_data.push(entry_data);
                    }
                }
            } else {
                let definition = if quizlet_minimal || example_raw.is_empty() {
                    format!("{} / {}", english, ukrainian)
                } else {
                    format!("{} / {} | {}", english, ukrainian, example_raw)
                };
                let output_line = format!("{}\t{}\n", word_display, definition);
                all_entries.push(output_line.clone());
                if !seen.contains_key(&word_display) {
                    unique_entries_str.push(output_line);
                    seen.insert(word_display.clone(), fname.clone());
                }
            }
        }
    }

    if format_type == "anki" {
        let anki_dir = PathBuf::from("anki");
        fs::create_dir_all(&anki_dir).unwrap();
        let apkg_name = format!("Anki_{}.apkg", base_name);
        let mut package = Package::new(vec![deck], vec![]).unwrap();
        let out_path = anki_dir.join(apkg_name);
        package.write_to_file(out_path.to_str().unwrap()).unwrap();

        if base_name == "B1plus_B2" {
            let web_dir = PathBuf::from("docs");
            fs::create_dir_all(&web_dir).unwrap();
            let json = serde_json::to_string_pretty(&web_data).unwrap();
            fs::write(web_dir.join("data.json"), json).unwrap();
            println!("✅ Web data exported to docs/data.json ({} unique entries)", web_data.len());
        }
    } else {
        let out_dir = PathBuf::from("quizlet");
        fs::create_dir_all(&out_dir).unwrap();
        let suffix = if quizlet_minimal { "_Minimal.txt" } else { "_Full.txt" };
        let filename_full = format!("Quizlet_{}{}", base_name, suffix);
        fs::write(out_dir.join(filename_full), all_entries.join("")).unwrap();
        
        let suffix_clean = if quizlet_minimal { "_Minimal_Clean.txt" } else { "_Clean.txt" };
        let filename_clean = format!("Quizlet_{}{}", base_name, suffix_clean);
        fs::write(out_dir.join(filename_clean), unique_entries_str.join("")).unwrap();
    }

    (all_entries.len(), unique_entries_str.len(), warnings)
}
